--- 
ec: ^ec\d\d\d\d\d\d$
dk: ^\d\d\d\d$
my: ^\d\d\d\d\d$
at: ^\d\d\d\d$
sk: ^\d\d\s?\d\d\d$
pr: ^\d\d\d\d\d$
rs: ^\d\d\d\d\d\d$
jp: ^\d\d\d\-?\d\d\d\d$
kh: ^\d\d\d\d\d$
au: ^\d\d\d\d$
cv: ^\d\d\d\d$
tc: ^\D\D\D\D\d\D\D$
kz: ^\d\d\d\d\d\d$
sm: ^\d\d\d\d\d$
gy: ^gy\d\s?\d\D\D$
pt: ^\d\d\d\d\s?\d\d\d$
ru: ^\d\d\d\d\d\d$
ac: ^\D\D\D\D\d\D\D$
ee: ^\d\d\d\d\d$
ad: ^ad\d\d\d$
tw: ^\d\d\d\d\d$
bn: ^\D\D\d\d\d\d$
ax: ^\d\d\d\d\d$
hr: ^\d\d\d\d\d$
lt: ^\d\d\d\d\d$
vg: ^vg\d\d\d\d$
cy: ^\d\d\d\d$
cz: ^\d\d\s?\d\d\d$
lu: ^\d\d\d\d$
fr: ^\d\d\d\d\d$
ch: ^\d\d\d\d$
az: ^az\d\d\d\d$
lv: ^lv\-?\d\d\d\d$
th: ^\d\d\d\d\d$
us: ^\d\d\d\d\d$
br: ^\d\d\d\d\d\-?\d\d\d$
il: ^\d\d\d\d\d$
hu: ^\d\d\d\d$
je: ^je\d\s?\d\D\D$
im: ^im\d\s?\d\D\D$
ph: ^\d\d\d\d$
ua: ^\d\d\d\d\d$
nz: ^\d\d\d\d$
in: ^\d\d\d\d$
io: ^\D\D\D\D\d\D\D$
ni: ^\d\d\d\d\d\d$
cl: ^\d\d\d\-?\d\d\d\d$
bb: ^bb\d\d\d\d\d$
li: ^\d\d\d\d$
vn: ^\d\d\d\d\d\d$
al: ^\d\d\d\d$
iq: ^\d\d\d\d\d$
cn: ^\d\d\d\d\d\d$
pl: ^\d\d\-?\d\d\d$
kr: ^\d\d\d\-?\d\d\d$
ma: ^\d\d\d\d\d$
bd: ^\d\d\d\d$
de: ^\d\d\d\d\d$
am: ^\d\d\d\d$
co: ^\d\d\d\d\d\d$
lk: ^\d\d\d\d\d$
nl: ^\d\d\d\d\s?\D\D$
se: ^\d\d\d\s?\d\d$
mt: ^\D\D\D\s?\d\d\d\d$
be: ^\d\d\d\d$
is: ^\d\d\d$
pn: ^\D\D\D\D\d\D\D$
ro: ^\d\d\d\d\d\d$
gr: ^\d\d\d\d\d$
dz: ^\d\d\d\d\d$
bg: ^\d\d\d\d$
za: ^\d\d\d\d$
fi: ^\d\d\d\d\d$
md: ^md\-?\d\d\d\d$
sg: ^\d\d\d\d\d\d$
gs: ^\D\D\D\D\d\D\D$
it: ^\d\d\d\d\d$
tr: ^\d\d\d\d\d$
cr: ^\d\d\d\d\d$
es: ^\d\d\d\d\d$
me: ^\d\d\d\d\d$
mx: ^\d\d\d\d\d$
ar: ^\D\d\d\d\d$
ca: ^\D\d\D$
fk: ^\D\D\D\D\d\D\D$
"no": ^\d\d\d\d$
si: ^si\-?\d\d\d\d$
va: ^\d\d\d\d\d$